### ISSUE TITLE
python 3.11 version

### ISSUE THREAD

**Issue by petrushy** [conda-forge/jpype1-feedstock#47]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

No 3.11 version built.

### Installed packages

```shell
none
```

### Environment info

```shell
none
```

**Comment by petrushy** [comment]
Hi, it seems like jpype 1.4.1 would support python 3.11 but the current build does not seem to include it.

An automatic bot request was initiated at https://github.com/conda-forge/jpype1-feedstock/pull/45 but closed. Maybe this can be rerendered on current version?

**Comment by jakirkham** [comment]
Guessing this is what PR ( https://github.com/conda-forge/jpype1-feedstock/pull/48 ) is trying to solve
